apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  labels:
    app.kubernetes.io/component: discovery
    app.kubernetes.io/instance: tidb-cluster
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: tidb-cluster
    helm.sh/chart: tidb-cluster-dev
  name: tidb-cluster-discovery
rules:
- apiGroups:
  - pingcap.com
  resourceNames:
  - tidb-cluster
  resources:
  - tidbclusters
  verbs:
  - get
