apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: monitor
    app.kubernetes.io/instance: tidb-cluster
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: tidb-cluster
    helm.sh/chart: tidb-cluster-dev
  name: tidb-cluster-prometheus
spec:
  ports:
  - name: prometheus
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app.kubernetes.io/component: monitor
    app.kubernetes.io/instance: tidb-cluster
    app.kubernetes.io/name: tidb-cluster
  type: NodePort
