apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: tidb
    app.kubernetes.io/instance: tidb-cluster
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: tidb-cluster
    helm.sh/chart: tidb-cluster-dev
  name: tidb-cluster-tidb
spec:
  ports:
  - name: mysql-client
    port: 4000
    protocol: TCP
    targetPort: 4000
  - name: status
    port: 10080
    protocol: TCP
    targetPort: 10080
  selector:
    app.kubernetes.io/component: tidb
    app.kubernetes.io/instance: tidb-cluster
    app.kubernetes.io/name: tidb-cluster
  type: NodePort
